### ISSUE TITLE
Souls Mod 1.10.2-1.0.2 doesn't play well with Ender IO 1.10.2-3.0.1.67_beta

### ISSUE THREAD

**Issue by kreezxil** [ChaosTheDude/Souls#1]
The SoulBound enchant.

When Souls mod is installed.

When a player dies.

A soul is spawned that has all the items a player had.

The soul wears the best items from the items it now has.

This includes soul bound items.

When the player respawns they do not have the soul bound items.

I am reporting this to the Ender IO too. https://github.com/SleepyTrousers/EnderIO/issues/3519

**Comment by ChaosTheDude** [comment]
Just tested with the same versions and did not encounter this. Soulbound items remained in the player's inventory as they should.
